name: Deploy Databricks bundle

on:
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: GitHub environment to use (dev/stg/prd)
  #       required: true
  #       default: dev
  #     target:
  #       description: Databricks bundle target (dev/stg/prd)
  #       required: true
  #       default: dev
  #     bundle_env:
  #       description: Bundle variable 'env' value
  #       required: true
  #       default: dev
  workflow_call:
    inputs:
      environment:
        description: GitHub environment to use (dev/stg/prd)
        required: false
        type: string
        default: dev
      # target:
      #   description: Databricks bundle target (dev/stg/prd)
      #   required: false
      #   type: string
      #   default: dev
      # bundle_env:
      #   description: Bundle variable 'env' value
      #   required: false
      #   type: string
      #   default: dev
  # push:
  #   branches: ["main"]

jobs:
  deploy:
    name: Deploy bundle
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}

    env:
      DATABRICKS_AUTH_TYPE: oauth-m2m
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      ENVIRONMENT: ${{ inputs.environment || 'dev' }}
      # BUNDLE_ENV: ${{ inputs.bundle_env || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
        with:
          version: 0.288.0

      - name: Validate bundle
        working-directory: bundles/geography
        run: databricks bundle validate -t "$ENVIRONMENT" --var env="$ENVIRONMENT"

      - name: Deploy bundle
        working-directory: bundles/geography
        run: databricks bundle deploy -t "$ENVIRONMENT" --var env="$ENVIRONMENT"